### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by AndresQuiVal** [rastvl/cloudflare-cookies-generator#1]
Hello there, I execute the exact same sample code as the given in [here](https://github.com/rastvl/cloudflare-cookies-generator/blob/main/repo/cloudflare-cookies-gen.gif) and yet I have the following error:

`{error: 'Failed to get cookies: timeout'}`

Also changed the URL to other cloudflare page based, and exactly the same error, does this solution still works??
@rastvl 

Thanks

**Comment by rastvl** [comment]
> Hello there, I execute the exact same sample code as the given in [here](https://github.com/rastvl/cloudflare-cookies-generator/blob/main/repo/cloudflare-cookies-gen.gif) and yet I have the following error:

Hello @AndresQuiVal, cloudflare was updated a couple of days ago. I haven't checked the changes yet.

**Comment by AndresQuiVal** [comment]
> 

Cool @rastvl , are you going to fix it? Thanks!

**Comment by rastvl** [comment]
> > 
> 
> Cool @rastvl , are you going to fix it? Thanks!

@AndresQuiVal There was a problem with the 2captcha extension code. Fixed.
I also noticed that another browser test has been added to the cloudflare page. Instead of hcaptcha, sometimes you have to click on an item. I may have to deal with this later.

**Comment by AndresQuiVal** [comment]
> > > 
> > 
> > 
> > Cool @rastvl , are you going to fix it? Thanks!
> 
> @AndresQuiVal There was a problem with the 2captcha extension code. Fixed. I also noticed that another browser test has been added to the cloudflare page. Instead of hcaptcha, sometimes you have to click on an item. I may have to deal with this later.

@rastvl Cool, seems that yet is not working, but we'll wait for the update of the package to be released!

**Comment by rastvl** [comment]
> Cool, seems that yet is not working, but we'll wait for the update of the package to be released!

@AndresQuiVal
At which site does the timeout occur? I checked on _temp-mail.org_ and got valid cookies

**Comment by AndresQuiVal** [comment]
It happens in https://www.innvictus.com/

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rastvl** [comment]
> It happens in https://www.innvictus.com/

@AndresQuiVal 
I don't get cloudflare on this page. Most likely the problem is that the browser does not get the cloudflare challenge page too. 
You can see what happens in the browser by changing the `headless` property in the `browserOptions` object in **constants.js** file to `false`

**Comment by AndresQuiVal** [comment]
Cool i will try then, but also, i tried with the webpage that was used on the gfi attached to this issue, and yet didnt work, and also tried with medium.com which seems to use cloudflare; neither of them worked, is that normal??

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rastvl** [comment]
> Cool i will try then, but also, i tried with the webpage that was used on the gfi attached to this issue, and yet didnt work, and also tried with medium.com which seems to use cloudflare; neither of them worked, is that normal??

@AndresQuiVal 
Much depends on your proxies. If the cloudflare challenge doesn't show up on your proxies, then you can work with the site without pre-installing the cookies, and you don't need this tool. 
I just tested on `https://www.zoominfo.com/c/Central-Florida-Athletics/363146903`, `https://temp-mail.org/`, `https://www.dekudeals.com/login` with "bad" ip where the cloudflare challenge triggered and it works fine. 
(Of course, I first installed the sitekey and rucaptcha api key in `constants.js`)

**Comment by AndresQuiVal** [comment]
@rastvl I tried with those urls:
`https://temp-mail.org/`
`https://www.dekudeals.com/login`

but none of them worked, still giving timeout error; but for this url:` https://www.zoominfo.com/c/Central-Florida-Athletics/363146903` it throw this error:

![image](https://user-images.githubusercontent.com/53063747/199373802-ae13e7e5-f431-4372-92d4-14b58181a6ba.png)

though was based on the captcha struggle the library has, yet don't know

Also, im not using proxies for all the sites im using the library with, so, still kind of trying to figure out why doesn't work :(

**Comment by rastvl** [comment]
> I tried with those urls:
> `https://temp-mail.org/`
> `https://www.dekudeals.com/login`

Have you enabled browser display in the `constants.js` file? I think that you from your ip just don't trigger the cloudflare challenge.


> throw this error:

This happens because you have not set the values of `hcaptcha_sitekey` and `capmonser_apikey` variables in the `constants.js` file

**Comment by AndresQuiVal** [comment]
@rastvl Cool, let me try then, how can I enable browser display? the current content of the `browserOptions` const is like this:


```
const browserOptions = {
  ignoreHTTPSErrors: true,
  args: [
    '--lang=en-US,en;q=0.9',
    '--disable-sync',
    '--disable-features=IsolateOrigins,site-per-process',
  ],
  defaultViewport: {
    width: 1920,
    height: 1080,
  },
  headless: true //,
  // proxy: { server: 'per-context' }
};
```

NOTE that proxy is commented

**Comment by rastvl** [comment]
> Cool, let me try then, how can I enable browser display?

`headless: false`

**Comment by AndresQuiVal** [comment]
@rastvl Still the same error after changing [that value](headless: false)
I tried with both urls and neither of those worked, still timeout error
`{error: 'Failed to get cookies: timeout'}`

**Comment by rastvl** [comment]
@AndresQuiVal Sorry, I'm not quite sure what you're doing. 
`headless: false` is so you can see if cloudflare triggers on your site.
[example](https://www.veed.io/view/b59a7c1f-3cc4-4afc-a1f7-c9330340eaa1)

**Comment by rastvl** [comment]
@AndresQuiVal [with hcaptcha ](https://www.veed.io/view/0f158cb5-d86f-4f22-b091-63bcd2634c73)

**Comment by AndresQuiVal** [comment]
> @AndresQuiVal [with hcaptcha ](https://www.veed.io/view/0f158cb5-d86f-4f22-b091-63bcd2634c73)

Sorry, I cannot se the video, seems to be unavailable, neither of the videos per se

**Comment by AndresQuiVal** [comment]
@rastvl After enabling the headless: false option, i've noticed that it opens the browser, but only keeps refreshing on the same site, i.e, refreshes on this part: 

![image](https://user-images.githubusercontent.com/53063747/199813593-b9f66f04-99dd-4e64-ad6a-e607d0553889.png)

is the webpage that it opened correct? or it should open other cloudflare site, such as the challenge?

**Comment by rastvl** [comment]
@AndresQuiVal are you using the latest version? This should work - [example](https://www.veed.io/view/dfef32ea-9610-453f-a6fe-ea3ec48e85d3)

**Comment by AndresQuiVal** [comment]
> 

Now it works for `dekudeals.com/login`
![image](https://user-images.githubusercontent.com/53063747/199819589-9fdb409e-f965-4ba3-afa2-c4013141d57a.png)

So then i realized something, the system can only solve the challenge and get the cookies whenever it appears on some resource of the webpage something like this:
![image](https://user-images.githubusercontent.com/53063747/199821225-d24f3859-193d-4cf6-a0e6-edbbc0c53210.png)

right? does there exists other way to get the cookies without having that page facing in?

**Comment by rastvl** [comment]
@AndresQuiVal 
> So then i realized something, the system can only solve the challenge and get the cookies whenever it appears on some resource of the webpage something like this

Yes, let's say I'm working with some web page through POST/GET requests. Because of cloudflare I get a 503 response and need to solve cloudlfare challange. In this case, I send a request to the server, the server should give cookies, and then I can continue to work with my web page using the received cookies.
(The system should run in headless mode to consume less RAM)

> does there exists other way to get the cookies without having that page facing in?

I don't really understand in what case it might be necessary. If the cloudflare page does not appear, I usually work with the site without any problems

**Comment by AndresQuiVal** [comment]
> 
Cool cool, now understand it, for other case scenario, I mean like cases in which the webpage throws some 429 status code, still that works? @rastvl

**Comment by rastvl** [comment]
> Cool cool, now understand it, for other case scenario, I mean like cases in which the webpage throws some 429 status code, still that works? @rastvl

@AndresQuiVal 429 is "too many requests" error. I guess, u need to use more proxies or increase the delay between requests)

**Comment by AndresQuiVal** [comment]
Thats perfect, now the main problem is solved, yet i tried to make a request using python code and didnt worked,
![image](https://user-images.githubusercontent.com/53063747/199827397-91c1faaf-0ce9-4c93-8d2b-d8765ef73119.png)
and the payload (python code) is like this:

 ```
def make_cookies():

    payload = {
        "url": "https://www.dekudeals.com/login", 
        "userAgent": f"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 100/104.0.0.0 Safari/537.36",
        "hcaptcha": ""
    }

    res = requests.post("http://localhost:3000/createTask", data=payload)
    res.raise_for_status()

    print(res.content)
```

Why is this happening?

**Comment by rastvl** [comment]
> Why is this happening?

@AndresQuiVal I don't use python, so I don't really understand what's wrong here. You need to figure out why you are sending the wrong request. 
I think the problem is in the `res = requests.post("http://localhost:3000/createTask", data=payload)`  line. Maybe you should write `res = requests.post("http://localhost:3000/createTask", json=payload)`

**Comment by AndresQuiVal** [comment]
@rastvl  Solved, that worked, thanks!

**Comment by AndresQuiVal** [comment]
Hello @rastvl seems that the library is again not working, i tested for  `dekudeals.com/login` and none of them worked, still seems to be the timeout error, does it work for you?

**Comment by rastvl** [comment]
> Hello @rastvl seems that the library is again not working, i tested for `dekudeals.com/login` and none of them worked, still seems to be the timeout error, does it work for you?

It works.
[Example](https://www.veed.io/view/f39978b2-8c5b-43b1-8909-a04bffad23f6)

**Comment by AndresQuiVal** [comment]
@rastvl I just redownloaded the library and execute it, removed the proxy use and set `headless : false` in `constants.js ` and yet doesnt work, is there something wrong with the configuration?

**Comment by rastvl** [comment]
@AndresQuiVal Alas, I don't know why it might not work for you. I also re-downloaded the files from the repository and got the cookies without any problems. Try looking at your browser that uses playwright.
I use chromium 105

**Comment by AndresQuiVal** [comment]
@rastvl just redownloaded the code again and not working, im using the sample script again and the chromium version is `107.0.5304`

**Comment by AndresQuiVal** [comment]
@rastvl What version of `playwright` are you using, seems that I'm using a latest version since your chromium version is different, or you specified an `executablePath` for chromium?

**UPDATE** @rastvl 

I tried using `chromium` version `105.0.5177.0` and doesnt work either, seems to be a package issue or something related to the source code, im still reading it to figure out but havent got to anything.

**Comment by AndresQuiVal** [comment]
@rastvl I made it work by cloning the project on macOS and moving it to my Windows PC, but I also tried with `www.innvictus.com` and the following page appears:
![image](https://user-images.githubusercontent.com/53063747/200669033-ee8341d6-5651-48a6-bcda-648268aa4c58.png)

How can we bypass that screen? how to handle that case if possible?

**Comment by AndresQuiVal** [comment]
Seems that cloning the project on MacOS, zipping the project and moving it to Windows worked, super strange even though where the same codebases, seems that those edge cases should be added to README.md in order for devs to consider it since we tried on 2 windows computers and none of them worked @rastvl
