### ISSUE TITLE
Failed to get cookies: timeout

### ISSUE THREAD

**Issue by Wi1y-project** [rastvl/cloudflare-cookies-generator#4]
Hi @rastvl, i've got a problem,  nomatter what url i request to router "createTask", when i request to router "checkTask" it's always return 
`{
    "error": "Failed to get cookies: timeout"
}`
and i'm sure the url that i request to router "createTask" is using cloudflare

**Comment by AndresQuiVal** [comment]
> 

Reference #1 to see solution @Wi1y-project

**Comment by Wi1y-project** [comment]
thx！
