### ISSUE TITLE
createTask An error occurred after the task was created

### ISSUE THREAD

**Issue by fomsun** [rastvl/cloudflare-cookies-generator#5]
App listening on port 3000
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.goto: net::ERR_EMPTY_RESPONSE at https://nowsecure.nl/
=========================== logs ===========================
navigating to "https://nowsecure.nl/", waiting until "load"
============================================================
    at PageHandler._goToUrl (/Users/sunlm/code/web/cloudflare-cookies-generator/libs/PageHandler.js:64:22) {
  name: 'Error'
}

**Comment by rastvl** [comment]
@lqdm Are you using a proxy?
from ReadMe: `proxy (required): Proxy of your project. (If you do not want to use a proxy, remove the line proxy: { server: 'per-context' } from browserOptions in the ./utils/constants.js file)`

**Comment by fomsun** [comment]
I removed the agent according to the method you provided, but now any website cannot be opened
The project will stop and exit for about a few seconds after the task is created 
I can't solve it at the moment

------
> cf-solver@1.0.0 start
> node index.js

App listening on port 3000
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.goto: net::ERR_PROXY_CONNECTION_FAILED at https://www.baidu.com/
=========================== logs ===========================
navigating to "https://www.baidu.com/", waiting until "load"
============================================================
    at PageHandler._goToUrl (/Users/sunlm/code/web/cloudflare-cookies-generator/libs/PageHandler.js:64:22) {
  name: 'Error'
}
-----
parameter body
{
"url":"https://www.baidu.com",
    "userAgent": "Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.101 Safari/537.36",
    "hcaptcha": ""
}

**Comment by fomsun** [comment]
The problem has been resolved. It's a problem with my local VPN

**Comment by fomsun** [comment]
I will turn off the VPN and everything will be fine. Thank you very much, buddy. Do you have the USDT payment address

**Comment by rastvl** [comment]
@lqdm I don't devote much time to this repository. I only update it when I need to, so no money is needed
